# Generated by Django 3.2.1 on 2023-07-03 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Время приготовления блюда', validators=[django.core.validators.MinValueValidator(1, message='Укажите время больше нуля!')], verbose_name='Время приготовления'),
        ),
    ]
